[package]
name = "banana-db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }
tabled = { version = "0.20.0", features = ["ansi"] }
